# Generated by Django 6.0.3 on 2026-04-03 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['date', 'record_type', 'category'], name='financial_r_date_f0fc67_idx'),
        ),
    ]
